# Generated by Django 5.2.17 on 2026-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (only visible to you)'), ('published', 'Published (visible in the public gallery)'), ('archived', 'Archived (kept on record, never public)')], default='draft', max_length=20),
        ),
    ]
