# Generated by Django 5.2.17 on 2026-09-29 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
